export { default as CategoryService } from './CategoryService'
export { default as ColorService } from './ColorService'
export { default as ProductService } from './ProductService'
export { default as PromotionService } from './PromotionService'
export { default as SizeService } from './SizeService'
export { default as UserService } from './UserService'
export { default as OrderService } from './OrderService'
export { default as HomeService } from './StatisTicalService'
export { default as AuthService } from './AuthService'
export { URL_IMG } from './http-common'
export { default as localStorageService } from './localStorageService'
